/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_davide_vegas_controller_BridgeServiceImpl */

#ifndef _Included_org_davide_vegas_controller_BridgeServiceImpl
#define _Included_org_davide_vegas_controller_BridgeServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_davide_vegas_controller_BridgeServiceImpl
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_davide_vegas_controller_BridgeServiceImpl_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
